import { Injectable } from '@angular/core';

/**
 * Responsive image descriptor generated by {@link ImageService}.
 */
export interface ResponsiveImage {
  /** Default `src` for the <img> element. */
  src: string;
  /** `srcset` with density-aware breakpoints. */
  srcset: string;
  /** Tiny width url used as a blurred placeholder (LQIP). */
  placeholder: string;
  /** Requested intrinsic width (px) for aspect-ratio / CLS control. */
  width: number;
}

/**
 * ImageService centralises every media-optimisation concern for the app:
 *
 *  - CDN sizing: Shopify-style CDNs let us request any width via a `width`
 *    query param, so we never download the original full-resolution file.
 *  - srcset: one request per visible viewport breakpoint (art direction).
 *  - LQIP: a ~24px thumbnail is used as a blurred placeholder, giving an
 *    instant "perceived load" before the real image arrives.
 *  - Preloading: hover/secondary images are fetched with the browser Image
 *    loader ahead of time (memoised) so swaps are instant.
 *
 * Every method is pure/immutable and result-cached to stay cheap under
 * change-detection pressure on large grids.
 */
@Injectable({ providedIn: 'root' })
export class ImageService {
  /** Widths used to build the responsive srcset. */
  readonly breakpoints = [320, 480, 640, 810, 1080, 1440] as const;
  readonly defaultWidth = 810;
  readonly lqipWidth = 24;

  private readonly urlCache = new Map<string, string>();
  private readonly preloadCache = new Map<string, Promise<void>>();

  /**
   * Build a size-optimised CDN url for `src` at `width`.
   * Any pre-existing width modifier is replaced (defensive).
   */
  buildUrl(src: string, width: number): string {
    const key = `${src}#w${width}`;
    const cached = this.urlCache.get(key);
    if (cached) return cached;

    let out = src;
    try {
      const url = new URL(src);
      url.searchParams.set('width', String(Math.round(width)));
      out = url.toString();
    } catch {
      // Non-absolute url (e.g. a base64/data image): keep as-is.
    }
    this.urlCache.set(key, out);
    return out;
  }

  /** Build a responsive `srcset` string for the given url. */
  buildSrcset(src: string, widths: readonly number[] = this.breakpoints): string {
    return widths
      .map((w) => `${this.buildUrl(src, w)} ${w}w`)
      .join(', ');
  }

  /** Blurred placeholder url used as the LQIP background. */
  placeholder(src: string): string {
    return this.buildUrl(src, this.lqipWidth);
  }

  /**
   * Build a complete responsive descriptor for an <img>.
   * Returns null when the src is not loadable.
   */
  build(src: string, width: number = this.defaultWidth): ResponsiveImage {
    return {
      src: this.buildUrl(src, width),
      srcset: this.buildSrcset(src),
      placeholder: this.placeholder(src),
      width,
    };
  }

  /**
   * Warm the browser image cache without painting. Memoised per url, so a
   * hover/secondary image is fetched exactly once and can be swapped in
   * instantly later. Settles (never rejects) so UI flow is unaffected.
   */
  preload(srcs: readonly string[]): Promise<void> {
    const tasks = srcs.map((src) => {
      const existing = this.preloadCache.get(src);
      if (existing) return existing;

      const task = new Promise<void>((resolve) => {
        const image = new Image();
        image.decoding = 'async';
        image.onload = () => resolve();
        image.onerror = () => resolve();
        image.src = src;
      });
      this.preloadCache.set(src, task);
      return task;
    });

    return Promise.all(tasks).then(() => undefined);
  }
}
